### ISSUE TITLE
train/test split mixed up?

### ISSUE THREAD

**Issue by MaxDall** [UniversalDependencies/UD_Buryat-BDT#2]
Since the test split is way bigger than the train split, could itt be that the two are mixed up? And in addition to that, would it be possible to create a dev split directly in the repository, since i want to add support for this dataset to flair.

**Comment by dan-zeman** [comment]
The treebank is too small to provide training, development and test sets of required sizes (at least 10K words is normally reserved for testing, and there is not much more than that in this treebank). The "training" data is just a tiny sample for people who want to do cross-lingual techniques and need a minimum to start. For more details, see the [data split guidelines](https://universaldependencies.org/release_checklist.html#data-split).

Users can of course train a model on the entire data for their own purposes, e.g. to get a parser that will preprocess data for further annotation. Of course they have to be careful if they report anything about such a parser in a paper. If they want to evaluate the accuracy of a supervised parser, they should use 10-fold cross-validation.
